### ISSUE TITLE
Cannot get expected result after sti build with this repo

### ISSUE THREAD

**Issue by wzheng1** [bparees/openshift-jee-sample#1]
Hi Ben, I tried to build with this repo via standalone STI command, it returns "FATA[0000] Error response from daemon: Cannot start container c1d758f20d6ea5a404e24407edc7119b1614941340b2f8d87198942683e31dc3: [8] System error: permission denied" when I run "docker run -p 8080:8080 wildflytest"; 
Below are my steps: 
1. Build with wildfly-8-centos image
$ sti build git://github.com/bparees/openshift-jee-sample openshift/wildfly-8-centos wildflytest
2. Check the result
$ docker run -p 8080:8080 wildflytest

Could you please help on this issue? Thanks in advance!

**Comment by bparees** [comment]
There's an issue in selinux/docker on fedora right now that prevents running scripts in /tmp.  Unfortunately that's where STI puts your run script if you provide an external script (don't use the one in the image).  The wildfly STI image pulls the scripts from an external location, so they end up in /tmp and you hit this failure.

you can work around this by running the container with --privileged

But i'm going to update the wildfly image to not use /tmp to work around the selinux problem.

**Comment by bparees** [comment]
fixed here: 
https://github.com/openshift/wildfly-8-centos/pull/39

please confirm/close.

**Comment by wzheng1** [comment]
Thanks, Ben! It works with the image I built locally with image id 806177d14ffd, closing this issue now.
