### ISSUE TITLE
Get error when sti build with "MAVEN_ARGS=clean package" with this repo

### ISSUE THREAD

**Issue by xiuwang** [bparees/openshift-jee-sample#2]
Hi Ben,could you help to check the following issue?
When sti build tomcat7-openshift/tomcat8-openshift/eap images with  "MAVEN_ARGS=clean package" with this repo, will meet error, http://fpaste.org/229825/44378143/.

Here is my command:  
sti build -e "MAVEN_ARGS=clean package" --loglevel=5 --force-pull=false  https://github.com/bparees/openshift-jee-sample openshift/tomcat7-openshift test-tomcat7-app

Thanks in advance!

**Comment by bparees** [comment]
you need "MAVEN_ARGS=clean package -Popenshift" due to the way the pom.xml in that project is constructed.

**Comment by xiuwang** [comment]
Thanks, I will try

**Comment by xiuwang** [comment]
Works with "MAVEN_ARGS=clean package -Popenshift" when sti build with this repo.

**Comment by bparees** [comment]
@xiuwang fyi i did update the readme to indicate that argument is needed.  thanks for finding the issue!
https://github.com/bparees/openshift-jee-sample/blob/master/README.md
